# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hilbert d to x, y
#'
#' @param n index
#' @param d hilbert cell coordinate
#' @export
d2xy <- function(n, d) {
    .Call('hilbert_d2xy', PACKAGE = 'hilbert', n, d)
}

#' Hilbert x, y to d
#'
#' @param n index
#' @param x,y coords
#' @export
xy2d <- function(n, x, y) {
    .Call('hilbert_xy2d', PACKAGE = 'hilbert', n, x, y)
}

